### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by Gallagator** [lschuermann/nur-packages#12]
The README doesn't contain instructions on how to use this. It's use seems to differ from [NUR](https://github.com/nix-community/NUR) from what I've seen. Or at least I can't get it to work. 

I'd really appreciate an example on how to use this as the vivado packages will be incredibly useful to me.

**Comment by lschuermann** [comment]
Hey, sorry for the late response! It's good to know that others are interested in this.

I would hope that this repository is not much different from other NURs. You should be able to do something like

```nix
# configuration.nix
environment.systemPackages = with pkgs; [
  nur.repos.lschuermann.vivado-2022_2
];
```
 after you follow the instructions in the [NUR README.md](https://github.com/nix-community/NUR/blob/6b482278399a9836fba8ad5b8a7628ab9456eefd/README.md).

However, doing this will yield an evaluation error that shows instructions on how to inject Vivado into the Nix store. Vivado is shipped as a _huge_ archive, and normal Nix tools choke on copying this into the Nix store (they copy it fully into memory). instead, there's a small dance that you have to go through to get this package imported, which is pointed to in the package source:

https://github.com/lschuermann/nur-packages/blob/2b2a38c754881dea3df08e1fe75076a21abcf2f4/pkgs/vivado/vivado-2022_2.nix#L38-L48

If you follow the instructions under that linked (copied below, where `largefile` must point to your Vivado archive as specified in the `name` attribute above), you should be able to add the Vivado source to your Nix store:

```bash
$ sudo unshare -m bash  # open a shell as root in a private mount namespace
$ largefile=/path/to/file
$ hash=$(nix-hash --type sha256 --flat --base32 $largefile)  # sha256 hash of the file
$ storepath=$(nix-store --print-fixed-path sha256 $hash $(basename $largefile))  # destination path in the store
$ mount -o remount,rw /nix/store  # remount the store in read/write mode (only for this session)
$ cp $largefile $storepath  # copy the file
$ printf "$storepath\n\n0\n" | nix-store --register-validity --reregister  # register the file in the Nix database
$ exit  # exit to the original shell where /nix/store is still mounted read-only
```

Hope this helps! Let me know if you have more questions.
